"""test runnnig migrations

Revision ID: 3089c0c4c55f
Revises: 1c910ffd5fbf
Create Date: 2025-09-02 23:25:17.032637

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3089c0c4c55f"
down_revision: Union[str, Sequence[str], None] = "1c910ffd5fbf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
