"""test runnnig migrations

Revision ID: 484c9c79f3e9
Revises: 2e7f945b2443
Create Date: 2025-09-03 16:11:14.445649

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "484c9c79f3e9"
down_revision: Union[str, Sequence[str], None] = "2e7f945b2443"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
