"""test runnnig migrations

Revision ID: 6d03a8f5e07f
Revises: 8c6dc8522aff
Create Date: 2025-09-02 22:41:26.276880

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "6d03a8f5e07f"
down_revision: Union[str, Sequence[str], None] = "8c6dc8522aff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
