"""test runnnig migrations

Revision ID: 8fdfb7fa79fa
Revises: 9a3bdfb8e236
Create Date: 2025-09-01 14:28:41.910983

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8fdfb7fa79fa"
down_revision: Union[str, Sequence[str], None] = "9a3bdfb8e236"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
