"""test runnnig migrations

Revision ID: cf7bb6a46e64
Revises: dec8ac5ad7fe
Create Date: 2025-09-02 23:20:48.467156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf7bb6a46e64'
down_revision: Union[str, Sequence[str], None] = 'dec8ac5ad7fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
