"""test runnnig migrations

Revision ID: dec8ac5ad7fe
Revises: 8de73f8d6999
Create Date: 2025-09-02 23:17:24.686893

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "dec8ac5ad7fe"
down_revision: Union[str, Sequence[str], None] = "8de73f8d6999"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
